package task6.exceptions.part2;

public class App1 {

    public static void main(String[] args) {
        launchFirstExample();
    }

    public static void launchFirstExample() throws RuntimeException {
    }

}
